---
booktitle: Proceedings of IJCAI 2018 2nd Workshop on Artificial Intelligence in Affective
  Computing
shortname: AFFCOMP
volume: 86
year: '2018'
start: 2018-08-20
end: 2018-08-20
published: 2020-04-27
url: http://proceedings.mlr.press
location: Stockholm, Sodermanland, Sweden
layout: proceedings
series: Proceedings of Machine Learning Research
id: AFFCOMP2018
month: 0
cycles: false
bibtex_editor: Hsu, William and Yates, Heath
editor:
- given: William
  family: Hsu
- given: Heath
  family: Yates
title: Proceedings of Machine Learning Research
description: |
  Proceedings of IJCAI 2018 2nd Workshop on Artificial Intelligence in Affective Computing on 20 August 2018

  Published as Volume 86 by the Proceedings of Machine Learning Research on 27 April 2020.

  Volume Edited by:
    William Hsu
    Heath Yates

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 20 Aug
baseurl: "/v86"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v86
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Workshop on Artificial Intelligence in Affective Computing
  url: 
  location: ''
  dates:
  - 2018-08-20
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from /Users/neil/mlresearch/v86/affcomp18.bib
